apiVersion: v1
kind: Secret
metadata:
  name: busybox-secret
data:
  username: YWRtaW4=
  password: c0NhbGVpbzEyMw==

---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: busybox
      namespace: default
      labels:
        app: busybox
        version: v1
    spec:
      containers:
      - image: busybox
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: busybox-secret           # The ConfigMap this value comes from.
              key: username # The key to fetch.
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: busybox-secret           # The ConfigMap this value comes from.
              key: password # The key to fetch.           
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox 
      restartPolicy: Always